### ISSUE TITLE
bracketeer_select - add quotes

### ISSUE THREAD

**Issue by certainlyakey** [colinta/SublimeBracketeer#5]
Hello! Thanks for the plugin.
I wonder, for `bracketeer_select` command, how do we add quotes to the expansion queue? That is, in your example code for this command after state 2 cursor jumps right to the curly braces. Is it possible to force it to make a stop inside quotes in `'test'` before that?

**Comment by katerlouis** [comment]
I absolutely would love an option on this one as well:

```json
{ "keys": ["super+alt+something"], "command": "bracketeer_select", "args": { "braces": "doublequotes" } },
```

`doublequotes` as a variable, since I fear `\"` would break something :D
